CREATE OR REPLACE FUNCTION public.saito_merge_tables (
  p_table_numbers integer[],
  p_performed_by  uuid      DEFAULT NULL::uuid
)
  RETURNS jsonb
  LANGUAGE plpgsql
  AS $function$ DECLARE v_primary_table INTEGER; v_child_tables INTEGER[]; v_primary_order_id UUID; v_child_order_ids UUID[]; v_child_total NUMERIC := 0; v_child_guests INTEGER := 0; v_merged_count INTEGER := 0; BEGIN IF array_length(p_table_numbers, 1) < 2 THEN RAISE EXCEPTION 'At least 2 tables required for merge' USING ERRCODE = 'P0002'; END IF; v_primary_table := p_table_numbers[1]; v_child_tables := p_table_numbers[2:]; SELECT id INTO v_primary_order_id FROM orders WHERE table_number = v_primary_table AND status NOT IN ('paid', 'cancelled', 'closed') LIMIT 1; IF v_primary_order_id IS NULL THEN INSERT INTO orders (table_number, status, order_type, guest_count, total_amount) VALUES (v_primary_table, 'new', 'dine_in', 0, 0) RETURNING id INTO v_primary_order_id; END IF; SELECT array_agg(id), COALESCE(SUM(total_amount), 0), COALESCE(SUM(guest_count), 0) INTO v_child_order_ids, v_child_total, v_child_guests FROM orders WHERE table_number = ANY(v_child_tables) AND status NOT IN ('paid', 'cancelled', 'closed'); IF v_child_order_ids IS NOT NULL AND array_length(v_child_order_ids, 1) > 0 THEN UPDATE orders SET merged_into = v_primary_order_id, version = COALESCE(version, 0) + 1 WHERE id = ANY(v_child_order_ids); UPDATE orders SET total_amount = COALESCE(total_amount, 0) + v_child_total, guest_count = COALESCE(guest_count, 0) + v_child_guests, version = COALESCE(version, 0) + 1 WHERE id = v_primary_order_id; v_merged_count := array_length(v_child_order_ids, 1); END IF; UPDATE table_floors SET status = 'merged', merged_into_table = v_primary_table, guest_count = 0, total_amount = 0, opened_at = NULL, last_activity_at = now() WHERE table_number = ANY(v_child_tables); UPDATE table_floors SET status = CASE WHEN status = 'empty' THEN 'ordering' ELSE status END, guest_count = COALESCE(guest_count, 0) + v_child_guests, last_activity_at = now() WHERE table_number = v_primary_table; INSERT INTO audit_log (table_name, record_id, action, old_data, new_data, performed_by, created_at) VALUES ('orders', v_primary_order_id, 'merge', jsonb_build_object('child_tables', v_child_tables), jsonb_build_object('merged_count', v_merged_count, 'child_total', v_child_total, 'child_guests', v_child_guests), p_performed_by, now()); RETURN jsonb_build_object('success', true, 'primary_table', v_primary_table, 'primary_order_id', v_primary_order_id, 'merged_count', v_merged_count, 'child_tables', v_child_tables, 'child_order_ids', v_child_order_ids, 'new_total', (SELECT COALESCE(total_amount, 0) FROM orders WHERE id = v_primary_order_id)); END; $function$;



