CREATE FUNCTION public.separate_tables_v1 (
  p_primary_table integer,
  p_child_tables  integer[],
  p_performed_by  uuid      DEFAULT NULL::uuid
)
  RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  AS $function$ DECLARE v_primary_order RECORD; v_child_order RECORD; v_removed_amount numeric := 0; v_removed_guests integer := 0; v_now timestamptz := now(); v_result jsonb; BEGIN SELECT id, total_amount, guest_count INTO v_primary_order FROM orders WHERE table_number = p_primary_table AND status NOT IN ('paid', 'cancelled', 'closed') AND merged_into IS NULL ORDER BY created_at DESC LIMIT 1; IF NOT FOUND THEN RAISE EXCEPTION 'PRIMARY_ORDER_NOT_FOUND' USING ERRCODE = 'P0001'; END IF; FOR i IN 1..array_length(p_child_tables, 1) LOOP SELECT id, total_amount, guest_count INTO v_child_order FROM orders WHERE table_number = p_child_tables[i] AND status NOT IN ('paid', 'cancelled', 'closed') AND merged_into = v_primary_order.id LIMIT 1; IF FOUND THEN v_removed_amount := v_removed_amount + COALESCE(v_child_order.total_amount, 0); v_removed_guests := v_removed_guests + COALESCE(v_child_order.guest_count, 0); UPDATE orders SET merged_into = NULL, table_number = p_child_tables[i], updated_at = v_now WHERE id = v_child_order.id; END IF; UPDATE table_floors SET status = CASE WHEN v_child_order.id IS NOT NULL THEN 'occupied' ELSE 'empty' END, guest_count = CASE WHEN v_child_order.id IS NOT NULL THEN v_child_order.guest_count ELSE NULL END, total_amount = CASE WHEN v_child_order.id IS NOT NULL THEN v_child_order.total_amount ELSE 0 END, merged_into_table = NULL WHERE table_number = p_child_tables[i]; END LOOP; UPDATE orders SET total_amount = GREATEST(COALESCE(v_primary_order.total_amount, 0) - v_removed_amount, 0), guest_count = GREATEST(COALESCE(v_primary_order.guest_count, 1) - v_removed_guests, 1), updated_at = v_now WHERE id = v_primary_order.id; UPDATE table_floors SET total_amount = GREATEST(COALESCE(v_primary_order.total_amount, 0) - v_removed_amount, 0), guest_count = GREATEST(COALESCE(v_primary_order.guest_count, 1) - v_removed_guests, 1), last_activity_at = v_now WHERE table_number = p_primary_table; INSERT INTO audit_log (table_name, record_id, action, old_data, new_data, changed_by) VALUES ('orders', v_primary_order.id::text, 'unmerge', jsonb_build_object('primary_table', p_primary_table, 'child_tables', p_child_tables), jsonb_build_object('removed_amount', v_removed_amount, 'removed_guests', v_removed_guests), p_performed_by); INSERT INTO notifications (title, body, type, data, created_at) VALUES ('Masalar ayrıldı', 'Masa ' || p_primary_table || ' — ' || array_length(p_child_tables, 1) || ' masa ayrıldı', 'order', jsonb_build_object('primary_table', p_primary_table, 'child_tables', p_child_tables), v_now); SELECT jsonb_build_object('success', true, 'primary_table', p_primary_table, 'child_tables', p_child_tables, 'removed_amount', v_removed_amount, 'removed_guests', v_removed_guests) INTO v_result; RETURN v_result; END; $function$;

GRANT ALL ON FUNCTION public.separate_tables_v1(integer, integer[], uuid) TO anon;

GRANT ALL ON FUNCTION public.separate_tables_v1(integer, integer[], uuid) TO authenticated;

GRANT ALL ON FUNCTION public.separate_tables_v1(integer, integer[], uuid) TO service_role;